config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'index' => 'home#index'
  get 'help' => 'home#help'
  get 'about' => 'home#about'
  get 'contact' => 'home#contact'
  get 'news' => 'home#news'
  get 'signup' => 'users#new'
  get 'dashboard' => 'profile#dashboard'

  # these routes are for showing users a login form, logging them in, and logging them out.
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def help
  end

  def about
  end

  def contact
  end

  def news
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_filter :authorize
  def dashboard

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to dashboard_path
    else
    # If user's login doesn't work, send them back to the login form.
      flash[:error] = "Wrong email or password"
      redirect_to '/login'
    end
  end

  def destroy
    flash[:error] = "You have been disconnected"
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user= User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to login_path
    else
      render 'new'
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :birthday, :surname, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/home/about.html.erb
<div class="row">
  <div class=" col-md-offset-1 col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">
          Contact us !
        </h3>
      </div>
      <div class="panel-body">
        You can contact us on the <%= link_to 'contact page', contact_path %>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">
          News
        </h3>
      </div>
      <div class="panel-body">
        Follow our activity on the <%= link_to 'news page', news_path %>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">
          Need help ?
        </h3>
      </div>
      <div class="panel-body">
        If you need help, go on <%= link_to 'help page', help_path %>
      </div>
    </div>
  </div>
</div>

app/views/home/contact.html.erb
<div class="container">
  <div class="col-md-offset-3 col-md-6">
    <div class="form-area">
      <form role="form">
        <br style="clear:both">
        <h3 style="margin-bottom: 25px; text-align: center;">Contact Form</h3>
        <div class="form-group">
          <input type="text" class="form-control" id="name" name="name" placeholder="Name" required>
        </div>
        <div class="form-group">
          <input type="text" class="form-control" id="email" name="email" placeholder="Email" required>
        </div>
        <div class="form-group">
          <input type="text" class="form-control" id="mobile" name="mobile" placeholder="Mobile Number" required>
        </div>
        <div class="form-group">
          <input type="text" class="form-control" id="subject" name="subject" placeholder="Subject" required>
        </div>
        <div class="form-group">
          <textarea class="form-control" type="textarea" id="message" placeholder="Message" maxlength="140" rows="7"></textarea>
        </div>

        <button type="button" id="submit" name="submit" class="btn btn-primary pull-right">Submit Form</button>
      </form>
    </div>
  </div>
</div>

app/views/home/help.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="headingOne">
          <h4 class="panel-title">
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              I can't log in
            </a>
          </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
          <div class="panel-body">
            No worries ! This feature is just not available.
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="headingTwo">
          <h4 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              I can't contact you by the contact page
            </a>
          </h4>
        </div>
        <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
          <div class="panel-body">
            It's actually a static page. You'll do nothing, be patient !
          </div>
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="headingThree">
          <h4 class="panel-title">
            <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
              News are never update
            </a>
          </h4>
        </div>
        <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
          <div class="panel-body">
              It's a static page. I'll not create other. I'm sorry ...
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="jumbotron center">
  <h1>Welcome to my Static App !</h1>
  <p>You're on my home page, have fun on this awesome website !</p>
  <p><a class="btn btn-primary btn-lg" href="#" role="button">Sign up now !</a></p>
</div>

<img style="width:100px;margin-left:20px;" src="http://www.prestagence.fr/wp-content/uploads/2013/07/Ruby_on_Rails_logo.jpg"

app/views/home/news.html.erb
<div class="row center">
  <div class="col-md-10 col-md-offset-1">
    <div class="jumbotron">
      <h1>Contact Page</h1>
      <p>Contact page is now available <%= link_to 'here', contact_path %></p>
      <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
    </div>
    <div class="jumbotron">
      <h1>Help Page</h1>
      <p>Help page is now available <%= link_to 'here', help_path %></p>
      <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
    </div>
    <div class="jumbotron">
      <h1>News Page</h1>
      <p>News page is now available <%= link_to 'here', news_path %></p>
      <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta http-equiv = "Content-Type" content = "text/html; charset = iso-8859-1" />
  <meta http-equiv = "Content-Language" content = "en-us" />
  <title>My App</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'SIMPLE APP',root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Home',root_path %></li>
          <li><%= link_to 'Help', help_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <b>
                <% if current_user %>
                <%= current_user.name %>
                <% else %>
                Login
                <% end %>
              </b>
              <span class="caret"></span>
            </a>
            <ul id="login-dp" class="dropdown-menu">
              <li>
                <div class="row">
                  <div class="col-md-12">
                    <% if current_user %>
                    <div id="user-menu">
                      Signed in as <b><%= current_user.name %></b>
                    </div>
                    <div class="form-group">
                      <%= link_to "Dashboard", dashboard_path %>
                    </div>
                    <div class="form-group">
                      <%= link_to "Logout", logout_path, class: "btn btn-primary btn-block" %>
                    </div>
                    <% else %>
                    <%= form_tag '/login' do %>
                    <div class="form-group">
                      <%= text_field_tag :email, nil, class: "form-control", placeholder: "Email"%>
                    </div>
                    <div class="form-group">
                      <%= password_field_tag :password, nil, class: "form-control", placeholder: "Password" %>
                    </div>
                    <div class="form-group">
                      <%= submit_tag "Submit", class:"btn btn-primary btn-block" %>
                    </div>
                    <% end %>
                    <div class="bottom text-center">
                      New here ? <b><%= link_to 'Join us', signup_path %></b>
                    </div>
                    <% end %>
                  </div>
                </li>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>

        <% if flash[:error] %>
        <div class="alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= flash[:error] %>
        </div>
        <% end %>
        <div id = "content">
          <%= yield -%>
        </div>

      </body>

      <footer class="footer">
        <div class="container">
          <span class="text-muted">The Ruby on Rails by Me</span>
          <span class="right">
            <%= link_to 'About',about_path %>
            <%= link_to 'Contact',contact_path %>
            <%= link_to 'News',news_path %>
          </span>
        </div>
      </footer>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h1>Sign up</h1>

    <%= form_for(@user) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class:"form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :birthday, "Birthday" %>
      <%= f.date_field :birthday, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :surname %>
      <%= f.text_field :surname, class:"form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, class:"form-control"%>
    </div>

    <div class="form-group">
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>


<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>